# Napari image viewer

Uses the octopuslite dask image loader to automatically sort and load images from multichannel time lapse experiments. Can also use btrack to load associated tracks and segmentation images.

In [1]:
import napari
from octopuslite import DaskOctopusLiteLoader

# batch testing transform implementation

In [ ]:
import os, glob

for transform in [8, 13]:
    expt = 'ND0010'
    pos = 'Pos0'
    for pos in range(0,12):
        pos = 'Pos'+str(pos)
        image_path = f'/home/nathan/data/kraken/ras/{expt}/{pos}/{pos}_images'
        transform_path = glob.glob(f'/home/nathan/data/kraken/ras/{expt}/{pos}/*transform_tensor_{transform}.npy')[0]
        if os.path.exists(image_path):
            print(expt, pos)
        #         trans = numpy.load(transform_path)
        #         if len(trans.shape) == 4:
        #             print('reshape')
        #             numpy.save(transform_path, numpy.reshape(trans, (len(trans)*len(trans[0]), 3, 3)))
            images = DaskOctopusLiteLoader(image_path, remove_background=False, 
                                           transforms=transform_path,
                                           crop = (1200, 1600))
            gfp = images['gfp']
        #     rfp = images['rfp']
        #     irfp = images['irfp']
        #     masks = images['mask']
            viewer = napari.Viewer()
            viewer.add_image(gfp,
                             contrast_limits=[0,255],
                             blending = 'additive', 
                             colormap = 'green',
                            name = f'transform_{transform}')#, is_pyramid=False)
        #     viewer.add_image(rfp, name="rfp", 
        #                      contrast_limits=[0,55], 
        #                      blending = 'additive', colormap = 'magenta')#, is_pyramid=False)
        #     viewer.add_image(irfp, name="irfp", 
        #          contrast_limits=[0,255], 
        #          blending = 'additive', colormap = 'cyan')#
        #     viewer.add_image(masks, name = f'trans {expt}/{pos}',
        #                     contrast_limits=[0,2],
        #                    blending = 'additive',)
            viewer.show(block=True)

ND0010 Pos0
Using cropping: (1200, 1600)


/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/dask/array/core.py:2857: RuntimeWarning: coroutine 'get_msg' was never awaited
  return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)


ND0010 Pos1
Using cropping: (1200, 1600)


Exception in callback BaseAsyncIOLoop._handle_events(566, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(566, 1)>
Traceback (most recent call last):
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/nathan/a

ND0010 Pos2
Using cropping: (1200, 1600)


Exception in callback BaseAsyncIOLoop._handle_events(596, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(596, 1)>
Traceback (most recent call last):
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/nathan/a

ND0010 Pos3
Using cropping: (1200, 1600)
ND0010 Pos4
Using cropping: (1200, 1600)


Exception in callback BaseAsyncIOLoop._handle_events(658, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(658, 1)>
Traceback (most recent call last):
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/nathan/analysis/miniconda3/envs/cellx/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/nathan/a

In [35]:
trans

array([[[[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1.89492439e+02],
         [ 0.00000000e+00,  1.00000000e+00,  9.49814865e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -6.04458164e+01],
         [ 0.00000000e+00,  1.00000000e+00,  3.90185511e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        ...,

        [[ 1.00000000e+00,  0.00000000e+00, -1.74360709e+00],
         [ 0.00000000e+00,  1.00000000e+00,  1.26813950e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1.87293586e+02],
         [ 0.00000000e+00,  1.00000000e+00,  1.00358695e+02],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1

In [3]:
transform_path = f'/home/nathan/data/kraken/ras/{expt}/{pos}/gfp_transform_tensor_{transform}.npy'

In [7]:
import numpy

In [14]:
trans = numpy.load(transform_path)

In [27]:
len(trans.shape)

4

In [26]:
trans_0.shape

(1190, 3, 3)

In [32]:
numpy.reshape(trans, (len(trans)*len(trans[0]), 3, 3))

array([[[   1.        ,    0.        ,    0.        ],
        [   0.        ,    1.        ,    0.        ],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        , -189.49243866],
        [   0.        ,    1.        ,   94.98148654],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,  -60.44581643],
        [   0.        ,    1.        ,   39.0185511 ],
        [   0.        ,    0.        ,    1.        ]],

       ...,

       [[   1.        ,    0.        ,   18.53088588],
        [   0.        ,    1.        ,    2.99109121],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,   15.84132734],
        [   0.        ,    1.        ,    2.72973152],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,   17.74622942],
        [   0.        ,    1.        ,    3.44644383],
        [   0.        ,    0.        ,    

In [ ]:
if len(trans.shape) == 4:
    np.save(transform_path, numpy.reshape(trans, (len(trans)*len(trans[0]), 3, 3))

In [19]:
trans

array([[[[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1.89492439e+02],
         [ 0.00000000e+00,  1.00000000e+00,  9.49814865e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -6.04458164e+01],
         [ 0.00000000e+00,  1.00000000e+00,  3.90185511e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        ...,

        [[ 1.00000000e+00,  0.00000000e+00, -1.74360709e+00],
         [ 0.00000000e+00,  1.00000000e+00,  1.26813950e+01],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1.87293586e+02],
         [ 0.00000000e+00,  1.00000000e+00,  1.00358695e+02],
         [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],

        [[ 1.00000000e+00,  0.00000000e+00, -1

In [18]:
numpy.reshape(trans, (1190, 3, 3))

array([[[   1.        ,    0.        ,    0.        ],
        [   0.        ,    1.        ,    0.        ],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        , -189.49243866],
        [   0.        ,    1.        ,   94.98148654],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,  -60.44581643],
        [   0.        ,    1.        ,   39.0185511 ],
        [   0.        ,    0.        ,    1.        ]],

       ...,

       [[   1.        ,    0.        ,   18.53088588],
        [   0.        ,    1.        ,    2.99109121],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,   15.84132734],
        [   0.        ,    1.        ,    2.72973152],
        [   0.        ,    0.        ,    1.        ]],

       [[   1.        ,    0.        ,   17.74622942],
        [   0.        ,    1.        ,    3.44644383],
        [   0.        ,    0.        ,    

In [9]:
transform_path_0 = f'/home/nathan/data/kraken/ras/{expt}/{pos}/gfp_transform_tensor.npy'

In [23]:
numpy.load(transform_path_0).shape

(1190, 3, 3)

In [25]:
trans_0 = numpy.load(transform_path_0)

# Load images

In [ ]:
# define experiment ID and select a position
expt = 'ND0010'
pos = 'Pos0'
# point to where the data is
root_dir = '/home/nathan/data/kraken/ras'
image_path = f'{root_dir}/{expt}/{pos}/{pos}_images'
transform_path = f'{root_dir}/{expt}/{pos}/gfp_transform_tensor.npy'
tracks_path = f'{root_dir}/{expt}/{pos}/tracks.h5'
# lazily load images
images = DaskOctopusLiteLoader(image_path, 
                               transforms = transform_path,
                               crop = (1200,1600),
                               remove_background = False)
images.channels

In [ ]:
gfp = images['gfp']
rfp = images['rfp']
irfp = images['irfp']
masks = images['mask']

In [ ]:
import numpy as np
for i in rfp[1109:1113]:
    print(np.mean(i.compute()))

### Add tracks

In [ ]:
import btrack
from btrack.utils import tracks_to_napari

#### iRFP tracks

In [ ]:
with btrack.dataio.HDF5FileHandler(tracks_path, 
                                   'r', obj_type='obj_type_1'
                                  ) as h:
    irfp_tracks = h.tracks

In [ ]:
irfp_tracks, irfp_properties, irfp_graph = tracks_to_napari(irfp_tracks, ndim = 2)

#### RFP tracks

In [ ]:
with btrack.dataio.HDF5FileHandler(tracks_path, 
                                   'r', obj_type='obj_type_2'
                                  ) as h:
    rfp_tracks = h.tracks

In [ ]:
rfp_tracks, rfp_properties, rfp_graph = tracks_to_napari(rfp_tracks, ndim = 2)

# Launch viewer

In [ ]:
viewer = napari.Viewer()
viewer.add_image(gfp, name="gfp", 
                 contrast_limits=[0,255],
                 blending = 'additive', colormap = 'green')#, is_pyramid=False)
viewer.add_image(rfp, name="rfp", 
                 contrast_limits=[0,55], 
                 blending = 'additive', colormap = 'magenta')#, is_pyramid=False)
viewer.add_image(irfp, name="irfp", 
                 contrast_limits=[0,255], 
                 blending = 'additive', colormap = 'cyan')#
viewer.add_image(masks, name = 'masks',
                contrast_limits=[0,255],
               blending = 'additive',)
viewer.add_tracks(irfp_tracks)
viewer.add_tracks(rfp_tracks)